#!/bin/csh

echo Extracting archive of OldLatex created on Wed May  6 00:23:45 GMT-0500 1992

set sm=`cat x??|sum`
if ("$sm" == "17223 77") then
	echo checksum ok
	cat x??|uncompress|tar xvf -
else
	echo "new checksum = $sm"
	echo "old checksum = 17223 77"
	echo "searching for corrupted files:"
set sm = `sum xaa`
if ("17223 77" == "$sm") then
echo xaa is ok
else
echo xaa is CORRUPTED
endif
endif
